---
- hosts: localhost
  connection: local
  sudo: yes
  vars:
    gcc_version: 4.8
    scl_name: blpdevtools
  remote_user: jenkins
  tasks:
  - name: temporary debug info
    shell: pwd
  - name: ensure rpmdevtools is installed
    yum: name=rpmdevtools state=latest
  - name: ensure yum-utils is installed
    yum: name=yum-utils state=latest
  - name: Install mock
    yum: name=mock state=latest
  - name: Install mock-scm
    yum: name=mock-scm state=latest
  - name : Ensure current user is in the mock group
    user: name=jenkins groups=mock append=yes
  - name: Run mock build
    shell: "mock -r {{ ansible_env.PWD }}/../files/mock-config-epel-7.cfg --verbose"
    async: 36000 # Wait up to 10 hours
    poll: 20
