---
- hosts: localhost
  connection: local
  sudo: yes
  remote_user: jenkins
  vars_files:
    - ../vars/default.yaml
  tasks:
    - name: Install Copr BLPDevTools repo.
      get_url: "url={{ copr_repo_url }}
               dest='/etc/yum.repos.d/blpdevtools.repo'
               mode=0440"

    - name: Import Copr GPG key.
      rpm_key:
        key: "{{ copr_repo_gpg_key_url }}"
        state: present

    - name: Install gcc-gfortran
      yum: name=gcc-gfortran state=latest

    - name: check gfortran version
      shell: "gfortran -v 2>&1 | grep 'gcc version' "
      register: version
      failed_when: " '{{ gcc_version }}' not in version.stdout"

    - name: Set git clone destination path
      set_fact: git_dest="{{ ansible_env.PWD }}/legacy_fortran_tests"

    - name: Create git clone destination directory
      file: path={{ git_dest }} state=directory

    - name: Clone legacy fortran tests from CodethinkLabs
      git: "repo={{ legacy_fortran_tests }}
            dest={{ git_dest }}"

    - name: Run legacy fortran tests
      command: chdir={{ git_dest }} ./runtests.sh
      register: result
      failed_when: "'failed' in result.stdout"

    - name: Compile a helloworld.f example
      command: gfortran ../files/helloworld.f -o helloworld
      register: command_result
      failed_when: "command_result.rc != 0"

    - name: Run helloworld example
      command: ./helloworld
      register: hello_result
      failed_when: "'Hello World' not in hello_result.stdout"
