---
gcc_version: 4.8.5
scl_name: blpdevtools
copr_repo_url: https://copr.fedorainfracloud.org/coprs/blpdevtools/gcc-gfortran/repo/epel-7/blpdevtools-gcc-gfortran-epel-7.repo
copr_repo_gpg_key_url: https://copr-be.cloud.fedoraproject.org/results/blpdevtools/gcc-gfortran/pubkey.gpg
legacy_fortran_tests: https://github.com/CodethinkLabs/legacy-fortran-tests
